[package]
name = "gpu-compositor-experiment"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
log = "0.4.29"
pollster = "0.4.0"
pretty_env_logger = "0.5.0"
wgpu = "27.0.1"
winit = "0.30.12"
